# Generated by Django 4.2.3 on 2023-08-12 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nm', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=50, null=True)),
                ('team_description', models.TextField(blank=True, null=True)),
                ('admins', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='nm.profile')),
            ],
        ),
    ]
