# Generated by Django 4.2.3 on 2023-08-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm', '0003_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(blank=True, default=True, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
